"""
Core simulation functions for the AI inference energy model.

This file contains reusable calculation logic only.  plotting,
markdown explanations, and thesis-specific discussion in the notebook.
"""

from __future__ import annotations

from dataclasses import dataclass
from typing import Callable, Dict, Iterable, Tuple

import numpy as np


@dataclass(frozen=True)
class PowerParams:
    """Power and facility parameters used by the energy model."""

    p_idle: float = 140.0
    p_execution_idle: float = 220.0
    p_active_avg: float = 450.0
    pue: float = 1.08
    execution_idle_fraction: float = 0.197


@dataclass(frozen=True)
class ClusterParams:
    """Cluster and queueing parameters."""

    total_gpus: int = 256
    mu: float = 0.2
    step_hours: float = 0.25
    num_steps: int = 96
    pod_size: int = 8


def scale_in_pods(c_target: np.ndarray | float, pod_size: int = 8) -> np.ndarray:
    """Round a target GPU count up to the nearest pod size."""

    return np.ceil(np.asarray(c_target, dtype=float) / pod_size) * pod_size


def build_diurnal_lambda(
    shape: Iterable[float],
    lambda_peak: float,
    step_hours: float = 0.25,
) -> Tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Create hourly and 15-minute demand curves from a normalized daily shape.

    Returns
    -------
    lambda_hourly:
        24 hourly request-rate values in requests/second.
    lambda_15min:
        Interpolated request-rate values at the chosen step resolution.
    hours_96:
        Time axis corresponding to lambda_15min.
    """

    shape_arr = np.asarray(shape, dtype=float)
    if shape_arr.size != 24:
        raise ValueError("shape must contain exactly 24 hourly values")

    lambda_hourly = shape_arr * lambda_peak
    hours_24 = np.arange(24)
    hours_96 = np.arange(0, 24, step_hours)
    lambda_15min = np.interp(hours_96, hours_24, lambda_hourly)

    return lambda_hourly, lambda_15min, hours_96


def daily_intensity_from_hourly(lambda_hourly: np.ndarray) -> Callable[[float], float]:
    """Return a function lambda(t) that maps hour-of-day to request rate."""

    def lambda_func(t: float) -> float:
        hour = int(t) % 24
        return float(lambda_hourly[hour])

    return lambda_func


def simulate_nhpp(
    lambda_func: Callable[[float], float],
    max_lambda: float,
    T: float,
) -> list[float]:
    """Simulate an NHPP over [0, T] hours using thinning.

    lambda_func and max_lambda are expressed in requests/second.
    Returned event times are expressed in hours.
    """

    if max_lambda <= 0:
        return []

    times: list[float] = []
    t = 0.0

    while t < T:
        t += np.random.exponential(1 / (max_lambda * 3600))
        if t < T and np.random.rand() <= lambda_func(t) / max_lambda:
            times.append(t)

    return times


def simulate_pareto_bursts(
    shape: float,
    T: float,
    lambda_peak: float,
    burst_rate_per_hour: float = 2.0,
    burst_window_hours: float = 0.01,
) -> tuple[list[float], list[float], list[int]]:
    """Generate Pareto burst arrivals over a T-hour window.

    Returns
    -------
    arrival_times:
        Individual burst-generated request times in hours.
    burst_times:
        Start time of each burst event in hours.
    burst_sizes:
        Number of requests generated by each burst event.
    """

    times: list[float] = []
    burst_times: list[float] = []
    burst_sizes: list[int] = []
    t = 0.0

    while t < T:
        t += np.random.exponential(1.0 / burst_rate_per_hour)
        if t < T:
            burst_size = int((np.random.pareto(shape) + 1) * int(lambda_peak * 10))
            burst_times.append(t)
            burst_sizes.append(burst_size)

            for _ in range(burst_size):
                times.append(t + np.random.uniform(0, burst_window_hours))

    return times, burst_times, burst_sizes


def bin_to_rate(
    arrivals: Iterable[float],
    num_steps: int = 96,
    step_hours: float = 0.25,
) -> np.ndarray:
    """Convert event times in hours to a binned request-rate array in req/s."""

    binned = np.zeros(num_steps)
    seconds_per_step = step_hours * 3600

    for t_arr in arrivals:
        bin_idx = int(t_arr / step_hours)
        if 0 <= bin_idx < num_steps:
            binned[bin_idx] += 1.0 / seconds_per_step

    return binned


# Backward-compatible name used in the notebook.
bin_to_15min_rate = bin_to_rate


def provisioning_arrays(
    lambda_arr: np.ndarray,
    mu: float,
    total_gpus: int,
    pod_size: int = 8,
) -> dict[str, np.ndarray]:
    """Create static, conservative, and aggressive provisioning arrays."""

    return {
        "Static": np.full(len(lambda_arr), total_gpus, dtype=float),
        "Conservative": np.minimum(
            scale_in_pods(lambda_arr / (0.78 * mu), pod_size), total_gpus
        ),
        "Aggressive": np.minimum(
            scale_in_pods(lambda_arr / (0.95 * mu), pod_size), total_gpus
        ),
    }


def apply_cold_start_lag(c_active: np.ndarray) -> np.ndarray:
    """Apply one-step scale-up lag and immediate scale-down.

    If target capacity increases, ready capacity stays at the previous value
    for one step. If target capacity decreases, capacity drops immediately.
    """

    c_ready = np.zeros_like(c_active, dtype=float)
    c_ready[0] = c_active[0]

    for t in range(1, len(c_active)):
        c_ready[t] = np.minimum(c_active[t], c_active[t - 1])

    return c_ready


def utilisation_arrays(
    lambda_arr: np.ndarray,
    c_active: np.ndarray,
    c_ready: np.ndarray,
    mu: float,
    total_gpus: int,
) -> dict[str, np.ndarray]:
    """Compute capacity and utilisation arrays."""

    capacity_target_qps = c_active * mu
    capacity_ready_qps = c_ready * mu

    rho_theoretical = np.where(
        capacity_target_qps > 0,
        lambda_arr / np.maximum(capacity_target_qps, 1e-9),
        0.0,
    )
    rho_effective = np.where(
        capacity_ready_qps > 0,
        lambda_arr / np.maximum(capacity_ready_qps, 1e-9),
        0.0,
    )
    global_rho = lambda_arr / (total_gpus * mu)

    return {
        "capacity_target_qps": capacity_target_qps,
        "capacity_ready_qps": capacity_ready_qps,
        "demand_qps": lambda_arr,
        "rho_theoretical": rho_theoretical,
        "rho_effective": rho_effective,
        "global_rho": global_rho,
    }


def gpu_state_arrays(
    c_ready: np.ndarray,
    rho_effective: np.ndarray,
    total_gpus: int,
    execution_idle_fraction: float = 0.197,
) -> dict[str, np.ndarray]:
    """Partition GPUs into active, execution-idle, and deep-idle states."""

    rho_state = np.minimum(rho_effective, 1.0)

    gpus_active = c_ready * rho_state * (1 - execution_idle_fraction)
    gpus_execution_idle = c_ready - gpus_active
    gpus_deep_idle = total_gpus - c_ready

    return {
        "rho_state": rho_state,
        "gpus_active": gpus_active,
        "gpus_execution_idle": gpus_execution_idle,
        "gpus_deep_idle": gpus_deep_idle,
        "active_ratio": gpus_active / total_gpus,
        "execution_idle_ratio": gpus_execution_idle / total_gpus,
        "deep_idle_ratio": gpus_deep_idle / total_gpus,
    }


def energy_arrays(
    c_ready: np.ndarray,
    rho_effective: np.ndarray,
    gpus_active: np.ndarray,
    gpus_deep_idle: np.ndarray,
    power: PowerParams = PowerParams(),
) -> dict[str, np.ndarray | float]:
    """Compute energy use per step and daily totals."""

    rho_state = np.minimum(rho_effective, 1.0)

    pure_active_power = gpus_active * power.p_active_avg
    active_overhead_power = (
        c_ready * rho_state * power.execution_idle_fraction * power.p_execution_idle
    )
    inactive_idle_power = c_ready * (1 - rho_state) * power.p_execution_idle
    deep_idle_power = gpus_deep_idle * power.p_idle

    energy_pure_work = (pure_active_power * power.pue * 0.25) / 1000
    energy_active_overhead = (active_overhead_power * power.pue * 0.25) / 1000
    energy_inactive_idle = (inactive_idle_power * power.pue * 0.25) / 1000
    energy_deep_idle = (deep_idle_power * power.pue * 0.25) / 1000

    energy_total = (
        energy_pure_work
        + energy_active_overhead
        + energy_inactive_idle
        + energy_deep_idle
    )
    energy_ideal = (pure_active_power * 1.0 * 0.25) / 1000

    return {
        "energy_pure_work": energy_pure_work,
        "energy_active_overhead": energy_active_overhead,
        "energy_inactive_idle": energy_inactive_idle,
        "energy_deep_idle": energy_deep_idle,
        "energy_total": energy_total,
        "energy_ideal": energy_ideal,
        "total_kwh": float(np.sum(energy_total)),
        "work_kwh": float(np.sum(energy_pure_work)),
        "overhead_kwh": float(np.sum(energy_active_overhead)),
        "idle_kwh": float(np.sum(energy_inactive_idle)),
        "deep_kwh": float(np.sum(energy_deep_idle)),
        "ideal_total_kwh": float(np.sum(energy_ideal)),
    }


def run_one(
    lambda_arr: np.ndarray,
    c_active_arr: np.ndarray,
    mu: float = 0.2,
    total_gpus: int = 256,
    power: PowerParams = PowerParams(),
) -> dict[str, float | int]:
    """Run one strategy/arrival combination and return summary metrics."""

    c_ready = apply_cold_start_lag(c_active_arr)
    util = utilisation_arrays(lambda_arr, c_active_arr, c_ready, mu, total_gpus)
    states = gpu_state_arrays(
        c_ready,
        util["rho_effective"],
        total_gpus,
        power.execution_idle_fraction,
    )
    energy = energy_arrays(
        c_ready,
        util["rho_effective"],
        states["gpus_active"],
        states["gpus_deep_idle"],
        power,
    )

    return {
        "total": energy["total_kwh"],
        "pure": energy["work_kwh"],
        "oh": energy["overhead_kwh"],
        "inact": energy["idle_kwh"],
        "deep": energy["deep_kwh"],
        "mean_rho": float(np.mean(util["rho_effective"])),
        "max_rho": float(np.max(util["rho_effective"])),
        "sla_viol": int(np.sum(util["rho_effective"] > 1.0)),
    }


def run_strategy_comparison(
    lambda_sets: dict[str, np.ndarray],
    mu: float = 0.2,
    total_gpus: int = 256,
    pod_size: int = 8,
    power: PowerParams = PowerParams(),
) -> dict[str, dict[str, dict[str, float | int]]]:
    """Run Static/Conservative/Aggressive for each arrival process."""

    results: dict[str, dict[str, dict[str, float | int]]] = {}

    for arrival_name, lambda_arr in lambda_sets.items():
        results[arrival_name] = {}
        provisioning = provisioning_arrays(lambda_arr, mu, total_gpus, pod_size)

        for strategy_name, c_active in provisioning.items():
            results[arrival_name][strategy_name] = run_one(
                lambda_arr=lambda_arr,
                c_active_arr=c_active,
                mu=mu,
                total_gpus=total_gpus,
                power=power,
            )

    return results
